# 行列演算の基礎

$$\boldsymbol{w} = {\boldsymbol{x}^T}\boldsymbol{x}^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [2]:
import numpy as np

In [5]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [7]:
# 行列の定義
X = np.array([[1,2], [3,4]])
print (X)

[[1 2]
 [3 4]]


In [9]:
# 転置
print(X.T)

[[1 3]
 [2 4]]


In [10]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [19]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [20]:
x.T

array([1, 2, 3])

In [23]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [26]:
x.T

array([[1],
       [2],
       [3]])

In [27]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [33]:
row, col = X.shape
print(X.shape)

(2, 3)


In [32]:
X = np.array([[2,3,4],[1,2,3]])
print(X)

[[2 3 4]
 [1 2 3]]


In [34]:
for x in X:
  print(x)
  print('--')

[2 3 4]
--
[1 2 3]
--


# 演習問題

In [51]:
X = np.array([
  [1,2,3],
  [1,2,5],
  [1,3,4],
  [1,5,9]
])
y = np.array([[1],[5],[6],[8]])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [40]:
# Step1: X^T X
XTX = X.T.dot(X)
print(XTX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [50]:
# Step2: (X^T X)^-1
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [52]:
# Step3: X^T y
XTy = X.T.dot(y)
print(XTy)

[[ 20]
 [ 70]
 [124]]


In [53]:
# Step4: w = (XTX)^-1 X^T y
w = XTX_inv.dot(XTy)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [57]:
# import sklearn
from sklearn.linear_model import LinearRegression

In [65]:
# モデルの宣言
#model = LinearRegression()
model = LinearRegression(fit_intercept=False)


In [66]:
# モデルの学習 := パラメータの調整
model.fit(X,y)

LinearRegression(fit_intercept=False)

In [67]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [68]:
model.intercept_

0.0

In [70]:
# 予測精度 <- 決定係数 0-1の範囲。大きいほど良い
model.score(X, y)

0.6923076923076923

In [73]:
# 予測値の計算
x = np.array([[1,2,3]])

In [75]:
y_pred = model.predict(x)
y_pred

array([[3.]])